# Generated by Django 4.1 on 2022-08-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='blogName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='github_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=1, upload_to='about/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='lk_in_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='subTitle',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='tw_link',
            field=models.URLField(default=10),
            preserve_default=False,
        ),
    ]
